
apiVersion: v1
kind: Secret
metadata:
  name: my-mysql
type: Opaque
stringData:
  mysql-root-password: "my-secret-pw"
  database-url: "mysql://root:my-secret-pw@my-mysql-service.default.svc.cluster.local:3306/books"
  db-name: "books"
  db-user: "bookmanager"
  db-password: "userpassword123"
