apiVersion: v1
kind: Secret
metadata:
  name: my-mysql
type: Opaque
stringData:
  mysql-root-password: "my-secret-pw"  # Change this!
  database-url: "mysql://root:my-secret-pwe@my-mysql.default.svc.cluster.local:3306/books"  # Change password here too!