apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  labels:
    app: nextjs
spec:
  type: LoadBalancer
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-mysql-service
  labels:
    app: my-mysql
spec:
  type: ClusterIP
  selector:
    app: my-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306